services:
  gateway:
    build: ./gateway
    ports:
      - "5050:5050"
    depends_on:
      - user-service
    networks:
      - microservices-network
    volumes:
      - ./gateway:/app
      - ./gateway/node_modules:/app/node_modules
    environment:
      - PORT=5050
      - USER_SERVICE_URL=http://user-service:5002

  user-service:
    build: ./user-service
    ports:
      - "5002:5002"
    networks:
      - microservices-network
    depends_on:
      - postgres
    volumes:
      - ./user-service:/app
      - ./user-service/node_modules:/app/node_modules
    environment:
      - PORT=5002
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/user_db
      - JWT_SECRET=your_jwt_secret_key_here
    command: sh -c "npx prisma migrate deploy && npm start"

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - microservices-network
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "8080:80"
    networks:
      - microservices-network
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@simplehot.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

networks:
  microservices-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data: 