version: '3.8'

services:
  gateway:
    build: 
      context: ../gateway
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    depends_on:
      - user-service
    networks:
      - microservices-network
    volumes:
      - ..:/workspace:cached
      - ${HOME}/.npmrc:/root/.npmrc:ro
    environment:
      - PORT=5050
      - USER_SERVICE_URL=http://user-service:5002
    command: /bin/sh -c "while sleep 1000; do :; done"

  user-service:
    build: 
      context: ../user-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    networks:
      - microservices-network
    depends_on:
      - postgres
    volumes:
      - ..:/workspace:cached
      - ${HOME}/.npmrc:/root/.npmrc:ro
    environment:
      - PORT=5002
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/user_db
      - JWT_SECRET=your_jwt_secret_key_here
    command: /bin/sh -c "while sleep 1000; do :; done"

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - microservices-network
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

networks:
  microservices-network:
    driver: bridge

volumes:
  postgres-data: 